import type { JobPosting, Skill, SkillMeta, Worker } from "./types";

export const SKILL_META: SkillMeta[] = [
  { key: "PLUMBER", labelKey: "skill_PLUMBER", color: "text-trade-plumber", bg: "bg-trade-plumber/10" },
  { key: "ELECTRICIAN", labelKey: "skill_ELECTRICIAN", color: "text-trade-electrician", bg: "bg-trade-electrician/10" },
  { key: "CLEANER", labelKey: "skill_CLEANER", color: "text-trade-cleaner", bg: "bg-trade-cleaner/10" },
  { key: "PAINTER", labelKey: "skill_PAINTER", color: "text-trade-painter", bg: "bg-trade-painter/10" },
  { key: "MASON", labelKey: "skill_MASON", color: "text-trade-mason", bg: "bg-trade-mason/10" },
  { key: "DRIVER", labelKey: "skill_DRIVER", color: "text-trade-driver", bg: "bg-trade-driver/10" },
  { key: "IT_SUPPORT", labelKey: "skill_IT_SUPPORT", color: "text-trade-it", bg: "bg-trade-it/10" },
  { key: "SOFTWARE_ENGINEER", labelKey: "skill_SOFTWARE_ENGINEER", color: "text-trade-software", bg: "bg-trade-software/10" },
  { key: "WEDDING_PLANNER", labelKey: "skill_WEDDING_PLANNER", color: "text-trade-wedding", bg: "bg-trade-wedding/10" },
  { key: "CHEF", labelKey: "skill_CHEF", color: "text-trade-chef", bg: "bg-trade-chef/10" },
  { key: "HOME_WORKER", labelKey: "skill_HOME_WORKER", color: "text-trade-home", bg: "bg-trade-home/10" },
  { key: "FITNESS_TRAINER", labelKey: "skill_FITNESS_TRAINER", color: "text-trade-fitness", bg: "bg-trade-fitness/10" },
  { key: "EVENT_SERVICES", labelKey: "skill_EVENT_SERVICES", color: "text-trade-events", bg: "bg-trade-events/10" },
];

export function skillMeta(skill: Skill): SkillMeta {
  return SKILL_META.find((s) => s.key === skill)!;
}

export const WORKERS: Worker[] = [
  {
    id: "w1",
    name: "Jean Mugisha",
    skill: "PLUMBER",
    secondarySkills: ["MASON"],
    neighborhood: "Kimironko",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 132,
    rateRwf: 3500,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 214,
    yearsActive: 3,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 123 456",
    bio: "Specialist in pipe repair, water heater installation, and bathroom fittings. Fast response across Gasabo district.",
    available: true,
  },
  {
    id: "w2",
    name: "Keza Umutoni",
    skill: "CLEANER",
    neighborhood: "Kacyiru",
    city: "Kigali",
    nidVerified: true,
    rating: 4.9,
    ratingCount: 201,
    rateRwf: 8000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 340,
    yearsActive: 4,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 456 789",
    bio: "Deep home cleaning, laundry, and post-construction cleanup. Brings own eco-friendly supplies on request.",
    available: true,
  },
  {
    id: "w3",
    name: "Eric Kwizera",
    skill: "ELECTRICIAN",
    neighborhood: "Remera",
    city: "Kigali",
    nidVerified: true,
    rating: 4.7,
    ratingCount: 98,
    rateRwf: 4500,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1601582589907-f92af5ed9db8?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 156,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 987 654",
    bio: "Certified in household wiring, solar backup systems, and safety inspections. Available for emergency call-outs.",
    available: false,
  },
  {
    id: "w4",
    name: "Aline Mukamana",
    skill: "PAINTER",
    neighborhood: "Nyamirambo",
    city: "Kigali",
    nidVerified: true,
    rating: 4.6,
    ratingCount: 64,
    rateRwf: 7000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 88,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 222 333",
    bio: "Interior and exterior painting with clean, precise finishing. Free color consultation for full-house jobs.",
    available: true,
  },
  {
    id: "w5",
    name: "Emmanuel Habimana",
    skill: "MASON",
    secondarySkills: ["PLUMBER"],
    neighborhood: "Gikondo",
    city: "Kigali",
    nidVerified: false,
    rating: 4.5,
    ratingCount: 41,
    rateRwf: 9000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 52,
    yearsActive: 1,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 111 222",
    bio: "Block-laying, plastering, and small renovation work. NID verification in progress.",
    available: true,
  },
  {
    id: "w6",
    name: "Diane Ingabire",
    skill: "CLEANER",
    neighborhood: "Kicukiro",
    city: "Kigali",
    nidVerified: true,
    rating: 4.9,
    ratingCount: 176,
    rateRwf: 2500,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 289,
    yearsActive: 5,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 555 444",
    bio: "Trusted household help for cooking, cleaning, and childcare support. References available on request.",
    available: true,
  },
  {
    id: "w7",
    name: "Patrick Ndayisenga",
    skill: "PLUMBER",
    neighborhood: "Remera",
    city: "Kigali",
    nidVerified: true,
    rating: 4.4,
    ratingCount: 57,
    rateRwf: 3000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 71,
    yearsActive: 1,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 333 111",
    bio: "Quick fixes for leaks, blocked drains, and toilet installations. Weekend availability.",
    available: true,
  },
  {
    id: "w8",
    name: "Grace Uwase",
    skill: "PAINTER",
    neighborhood: "Kimironko",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 112,
    rateRwf: 7500,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 130,
    yearsActive: 3,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 777 888",
    bio: "Specialist in feature walls, gate touch-ups, and waterproof exterior coatings.",
    available: true,
  },
  {
    id: "w9",
    name: "Bosco Niyonzima",
    skill: "ELECTRICIAN",
    neighborhood: "Nyamirambo",
    city: "Kigali",
    nidVerified: true,
    rating: 4.6,
    ratingCount: 83,
    rateRwf: 4000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 99,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 666 999",
    bio: "Generator installation, socket repairs, and full rewiring for older homes.",
    available: true,
  },
  {
    id: "w10",
    name: "Solange Nyirahabimana",
    skill: "MASON",
    neighborhood: "Kacyiru",
    city: "Kigali",
    nidVerified: true,
    rating: 4.7,
    ratingCount: 45,
    rateRwf: 8500,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1580216643062-cf460548a66a?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 60,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 444 222",
    bio: "Compound paving, boundary walls, and tiling. Works with a 2-person crew for larger jobs.",
    available: false,
  },
  {
    id: "w11",
    name: "Claude Niyigena",
    skill: "DRIVER",
    secondarySkills: ["IT_SUPPORT"],
    neighborhood: "Kimironko",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 156,
    rateRwf: 1500,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1631281637549-9b6492f0d3e0?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 310,
    yearsActive: 6,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 111 444",
    bio: "Licensed private driver with defensive-driving certification. Reliable airport pickups, school runs, and errands across Kigali.",
    available: true,
  },
  {
    id: "w12",
    name: "Fidel Mbarushimana",
    skill: "IT_SUPPORT",
    neighborhood: "Remera",
    city: "Kigali",
    nidVerified: true,
    rating: 4.7,
    ratingCount: 89,
    rateRwf: 5000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 142,
    yearsActive: 3,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 222 555",
    bio: "Computer repair, network setup, and office IT support. Handles Windows and Mac, plus CCTV and Wi-Fi installations.",
    available: true,
  },
  {
    id: "w13",
    name: "Anita Uwase",
    skill: "SOFTWARE_ENGINEER",
    secondarySkills: ["IT_SUPPORT"],
    neighborhood: "Kacyiru",
    city: "Kigali",
    nidVerified: true,
    rating: 4.9,
    ratingCount: 73,
    rateRwf: 15000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 94,
    yearsActive: 4,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 333 666",
    bio: "Full-stack developer building websites, dashboards, and mobile apps. Clean code, clear communication, and timely delivery.",
    available: true,
  },
  {
    id: "w14",
    name: "Josiane Mukandoli",
    skill: "WEDDING_PLANNER",
    neighborhood: "Gisozi",
    city: "Kigali",
    nidVerified: true,
    rating: 4.9,
    ratingCount: 118,
    rateRwf: 25000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 167,
    yearsActive: 5,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 555 777",
    bio: "Full wedding protocol, from dowry ceremonies to reception. Vendor coordination, timelines, and day-of management.",
    available: true,
  },
  {
    id: "w15",
    name: "Theogene Rukundo",
    skill: "CHEF",
    neighborhood: "Kicukiro",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 96,
    rateRwf: 12000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 121,
    yearsActive: 3,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 666 888",
    bio: "Event and private catering — Rwandan, continental, and international menus. Brings full cooking setup for large gatherings.",
    available: true,
  },
  {
    id: "w16",
    name: "Vestine Uwimana",
    skill: "HOME_WORKER",
    neighborhood: "Kacyiru",
    city: "Kigali",
    nidVerified: true,
    rating: 4.7,
    ratingCount: 133,
    rateRwf: 7000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 205,
    yearsActive: 4,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 444 999",
    bio: "Dependable live-out household help — cooking, cleaning, laundry, and child supervision. Background checked and NID verified.",
    available: true,
  },
  {
    id: "w17",
    name: "Eric Byiringiro",
    skill: "FITNESS_TRAINER",
    neighborhood: "Kimironko",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 67,
    rateRwf: 10000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 88,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 777 333",
    bio: "Certified personal trainer and gymnastics coach. Home sessions, nutrition guidance, and group fitness for families.",
    available: true,
  },
  {
    id: "w18",
    name: "Sandrine Nyirahabimana",
    skill: "EVENT_SERVICES",
    neighborhood: "Kicukiro",
    city: "Kigali",
    nidVerified: true,
    rating: 4.6,
    ratingCount: 52,
    rateRwf: 40000,
    rateUnit: "day",
    photoUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 64,
    yearsActive: 3,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 888 111",
    bio: "Wedding and event equipment rental — tents, chairs, tables, and decorations. Delivery, setup, and teardown included.",
    available: true,
  },
  {
    id: "w19",
    name: "Olivier Nsengimana",
    skill: "DRIVER",
    neighborhood: "Nyamirambo",
    city: "Kigali",
    nidVerified: true,
    rating: 4.5,
    ratingCount: 44,
    rateRwf: 2000,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 78,
    yearsActive: 2,
    momoProvider: "AIRTEL_MONEY",
    momoNumber: "+250 738 555 444",
    bio: "Experienced driver for personal and business trips. Long-distance safaris and city tours with a well-maintained vehicle.",
    available: true,
  },
  {
    id: "w20",
    name: "Clarisse Umutoniwase",
    skill: "IT_SUPPORT",
    neighborhood: "Remera",
    city: "Kigali",
    nidVerified: true,
    rating: 4.8,
    ratingCount: 58,
    rateRwf: 4500,
    rateUnit: "hour",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=300&auto=format&fit=crop",
    jobsCompleted: 71,
    yearsActive: 2,
    momoProvider: "MTN_MOMO",
    momoNumber: "+250 788 999 222",
    bio: "IT troubleshooting, data backup, and software setup for homes and small businesses. Patient, clear explanations included.",
    available: true,
  },
];

export const JOBS: JobPosting[] = [
  {
    id: "j1",
    workerId: "w1",
    clientName: "You",
    clientPhone: "+250 788 000 111",
    taskDescription: "Fix leaking pipe under kitchen sink",
    scheduledFor: "2026-08-04T09:00:00",
    status: "CONFIRMED",
    depositRwf: 2000,
    createdAt: "2026-08-01T08:12:00",
  },
  {
    id: "j2",
    workerId: "w2",
    clientName: "You",
    clientPhone: "+250 788 000 111",
    taskDescription: "Full house deep cleaning before guests arrive",
    scheduledFor: "2026-07-28T08:00:00",
    status: "COMPLETED",
    depositRwf: 3000,
    createdAt: "2026-07-25T14:40:00",
  },
];

export const NEIGHBORHOODS = [
  "Kimironko",
  "Nyamirambo",
  "Kacyiru",
  "Remera",
  "Gikondo",
  "Kicukiro",
  "Kanombe",
  "Gisozi",
];
